[ADD] ws

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -29,3 +29,22 @@ jobs:
           fi
               echo "Everything is good ! Keep on coding !"
               exit 0
+
+  coding-style:
+    runs-on: ubuntu-latest
+    steps:
+      
+      - name: Checkout GH repository
+        uses: actions/checkout@master
+
+      - name: Compile repository
+        run: make
+
+      - name: Check binary presence
+        run: |
+          if [ ! -f ./swapupcase ]; then
+            echo "Binary not found"
+            exit 1
+          fi 
+            echo "Binary found"
+            exit 0
